nunu_panel/Controllers/PedidosController.cs
using Microsoft.AspNetCore.Mvc;
using nunu_panel.Models;
using System.Diagnostics;

namespace nunu_panel.Controllers
{
    public class PedidosController : Controller
    {
        private readonly ILogger<PedidosController> _logger;

        public PedidosController(ILogger<PedidosController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

nunu_panel/Controllers/UsuariosController.cs
using System.Collections.Generic;
using System.Diagnostics;
using System.Net;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using nunu_panel.Models;
using RestSharp;

namespace nunu_panel.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly ILogger<UsuariosController> _logger;

        public UsuariosController(ILogger<UsuariosController> logger)
        {
            _logger = logger;
        }

        private static readonly string apiBaseUrl = "https://api-nunu.igrtec.net/api/";

        public IActionResult Index()
        {
            var adminName = HttpContext.Session.GetString("AdminName");
            ViewBag.AdminName = adminName;
            var usuarios = GetUsuarios();
            return View(usuarios);
        }

        [HttpDelete]
        public IActionResult EliminarUsuario(int idUsuario)
        {
            var options = new RestClientOptions(apiBaseUrl) { MaxTimeout = -1 };

            var client = new RestClient(options);
            var request = new RestRequest($"/Usuarios/{idUsuario}", Method.Delete);
            var response = client.Execute(request);

            if (response.StatusCode == HttpStatusCode.NoContent)
            {
                string? content = response.Content;
                TempData["SuccessMensajeUsuario"] =
                    content != null ? $"¡Usuario {idUsuario} eliminado con éxito!" : null;
                return Ok(new { success = true, message = TempData["SuccessMensajeUsuario"] });
            }

            TempData["ErrorMensajeUsuario"] =
                $"Error al eliminar el usuario desde la API. {response.StatusCode}";
            return StatusCode(
                (int)response.StatusCode,
                new { success = false, message = TempData["ErrorEliminarUsuario"] }
            );
        }

        public List<UsuarioModel>? GetUsuarios()
        {
            try
            {
                var options = new RestSharp.RestClientOptions(apiBaseUrl) { MaxTimeout = -1 };

                var client = new RestSharp.RestClient(options);
                var request = new RestSharp.RestRequest("/Usuarios", Method.Get);
                var response = client.Execute<List<UsuarioModel>>(request);
                if (response.StatusCode == HttpStatusCode.OK)
                {
                    string? content = response.Content;
                    List<UsuarioModel>? usuarios = JsonConvert.DeserializeObject<
                        List<UsuarioModel>
                    >(content);
                    return usuarios;
                }
                else
                {
                    return null;
                }
            }
            catch
            {
                return null;
            }
        }

        public IActionResult Historial()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(
                new ErrorViewModel
                {
                    RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
                }
            );
        }
    }
}

nunu_panel/Views/Usuarios/Historial.cshtml
@{
    ViewData["Title"] = "Usuarios";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
 <a asp-controller="Usuarios" asp-action="Index" class="btn btn-link mt-1" style="color: gray;">
     <i class="fas fa-arrow-left"></i> Volver
 </a>
<div class="row mb-3">
    <div class="col">
        <form asp-controller="Pedidos" asp-action="Index">
            <div class="groupSearch">
                <svg class="iconSearch" aria-hidden="true" viewBox="0 0 24 24"><g><path d="M21.53 20.47l-3.66-3.66C19.195 15.24 20 13.214 20 11c0-4.97-4.03-9-9-9s-9 4.03-9 9 4.03 9 9 9c2.215 0 4.24-.804 5.808-2.13l3.66 3.66c.147.146.34.22.53.22s.385-.073.53-.22c.295-.293.295-.767.002-1.06zM3.5 11c0-4.135 3.365-7.5 7.5-7.5s7.5 3.365 7.5 7.5-3.365 7.5-7.5 7.5-7.5-3.365-7.5-7.5z"></path></g></svg>
                <input value="" name="searchTerm" placeholder="Busca por usuario/ID" type="search" class="inputSearch">
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="d-flex justify-content-between align-items-center">
        <h4 class="title-form">Usuarios</h4>
    </div>
</div>

<div class="row">
    <div class="breadcrumb">
        <a href="/Usuarios" class="breadcrumb-item active">Usuarios</a> >
    </div>
    Mostrando 7 de 100 resultados
</div>

<div class="col-md-12 mt-3">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col" class="textTableCenter">ID Compra</th>
                    <th scope="col" class="textTableCenter">Compras</th>
                    <th scope="col" class="textTableCenter">Proveedor</th>
                    <th scope="col" class="textTableCenter">Pago</th>
                    <th scope="col" class="textTableCenter">Fecha compra</th>
                    <th scope="col" class="textTableCenter">Estatus</th>
                    <th scope="col" class="textTableCenter">Calificación</th>
                    <th scope="col" class="textTableCenter"></th>
                </tr>
            </thead>
            <tbody> 
                <tr>                 
                    <td class="td-first">
                        000001
                    </td>
                    <td class="td-middle">Diseño</td>
                    <td class="td-middle">Lorem ipsum dolor</td>
                    <td class="td-middle">$5,550</td>
                    <td class="td-middle">00/00/0000</td>
                    <td class="td-middle"><span class="badge-custom por-aprobar" data-bs-toggle="modal" data-bs-target="#leftModal" style="cursor:pointer;">En camino</span></td>
                    <td class="td-middle"><a href ="#" data-bs-toggle="modal" data-bs-target="#calificacionModal">00/00</a></td>    
                    <td class="td-end">
                        <div class="dropdown">
                            <button class="btn dropdown-toggle text-dark" type="button" id="dropdownMenuButton1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-ellipsis-v"></i>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                <a class="dropdown-item" asp-controller="Home" asp-action="UsuarioDetalle">Contactar a usuario</a>
                                <a class="dropdown-item" asp-controller="Home" asp-action="UsuarioDetalle">Enviar Correo</a>
                                <a class="dropdown-item" asp-controller="Home" asp-action="UsuarioDetalle">Llamar</a>
                            </div>
                        </div>
                    </td>
                </tr>
                

            
            </tbody>
        </table>
    </div>
</div>




<div class="modal fade" id="calificacionModal" tabindex="-1" role="dialog" aria-labelledby="calificacionodalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title fw-bolder fs-3" id="estatusModalLabel">Calificación Del Servicio</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                 <div class="form-group">
                    <label for="">Comentario</label>
                    <input type="text" class="form-control" value="Estuvo Muy Mal El Servicio" readonly>
                </div>
                <div class="form-group">
                    <label for="">Calificación De La Experiencia</label>
                    <input type="text" class="form-control" value="00/00" readonly>
                </div>
                <div class="form-group">
                    <label for="">Calificación Del Proveedor</label>
                    <input type="text" class="form-control" value="00/00" readonly>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade modal-right" id="leftModal" tabindex="-1" aria-labelledby="leftModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="rightModalLabel">Devolución</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form>
                <p>Razón
                    <div class="form-group">
                        <label for="tipoCliente">Servicios</label>
                        <div class="input-group">
                            <select class="form-control" id="tipoCliente">
                                <option selected>Seleccionar...</option>
                                <option value="1">Cliente A</option>
                                <option value="2">Cliente B</option>
                                <option value="3">Cliente C</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="estatus">Estatus</label>
                        <div class="input-group">
                            <select class="form-control" id="estatus">
                                <option selected>Seleccionar...</option>
                                <option value="1">Activo</option>
                                <option value="2">Inactivo</option>
                                <option value="3">Pendiente</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="cumpleanos">Usuario</label>
                        <div class="input-group">
                            <div class="groupSearch">
                                <svg class="iconSearch" aria-hidden="true" viewBox="0 0 24 24"><g><path d="M21.53 20.47l-3.66-3.66C19.195 15.24 20 13.214 20 11c0-4.97-4.03-9-9-9s-9 4.03-9 9 4.03 9 9 9c2.215 0 4.24-.804 5.808-2.13l3.66 3.66c.147.146.34.22.53.22s.385-.073.53-.22c.295-.293.295-.767.002-1.06zM3.5 11c0-4.135 3.365-7.5 7.5-7.5s7.5 3.365 7.5 7.5-3.365 7.5-7.5 7.5-7.5-3.365-7.5-7.5z"></path></g></svg>
                                <input value="" name="searchTerm" placeholder="Busca por usuario/ID" type="search" class="inputSearch">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="cumpleanos">Proveedor</label>
                        <div class="input-group">
                            <div class="groupSearch">                                
                                <input value="" name="searchTerm" placeholder="Nombre" type="search" class="inputSearch">
                            </div>
                        </div>
                    </div>
                </form>
                <hr>
                <div class="filter-section">
                    <h6>Filtros aplicados</h6>
                    <div class="filters-applied">
                        <span class="tag">Tipo de Cliente <i class="fas fa-times close"></i></span>
                        <span class="tag">Buscar por Usuario <i class="fas fa-times close"></i></span>
                        <span class="tag">Estatus <i class="fas fa-times close"></i></span>
                        <span class="tag">Cumpleaños <i class="fas fa-times close"></i></span>
                    </div>
                </div>
                <button class="btn btn-primary w-100">Aplicar</button>
            </div>
        </div>
    </div>
</div>

nunu_panel/Views/Usuarios/Index.cshtml
@model List<nunu_panel.Models.UsuarioModel>

@{
    ViewData["Title"] = "Usuarios";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row mb-3">
        <div class="col-md-12">
            <div class="form-group">
                <input type="text" name="" id="searchInput" class="form-control" placeholder="Busca por usuario">
            </div>
            @* <form asp-controller="Usuarios" asp-action="Index">

                <div class="groupSearch">
                    <svg class="iconSearch" aria-hidden="true" viewBox="0 0 24 24">
                        <g>
                            <path
                                d="M21.53 20.47l-3.66-3.66C19.195 15.24 20 13.214 20 11c0-4.97-4.03-9-9-9s-9 4.03-9 9 4.03 9 9 9c2.215 0 4.24-.804 5.808-2.13l3.66 3.66c.147.146.34.22.53.22s.385-.073.53-.22c.295-.293.295-.767.002-1.06zM3.5 11c0-4.135 3.365-7.5 7.5-7.5s7.5 3.365 7.5 7.5-3.365 7.5-7.5 7.5-7.5-3.365-7.5-7.5z">
                            </path>
                        </g>
                    </svg>
                    <input value="" id="searchInput" name="searchTerm" placeholder="Busca por usuario/ID" type="search"
                        class="inputSearch">
                </div>
            </form> *@
        </div>
    </div>
    <div class="row">
        <div class="d-flex justify-content-between align-items-center">
            <h4 class="title-form">Usuarios</h4>
        </div>
    </div>

    <div class="row">
        <div class="breadcrumb">
            <a href="/Usuarios" class="breadcrumb-item active">Usuarios</a> >
        </div>
        @* Mostrando @Model.Count *@
    </div>

    <div class="col-md-12 mt-3">


        <table class="table" id="dataTable">
            <thead>
                <tr>
                    <th scope="col" class="">ID</th>
                    <th scope="col" class="">Cliente</th>
                    @* <th scope="col" class="textTableCenter">Dirección</th>
                    <th scope="col" class="textTableCenter">Ciudad</th>
                    <th scope="col" class="textTableCenter">Teléfono</th> *@
                    <th scope="col" class="">Fecha de registro</th>
                    <th scope="col" class="textTableCenter"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var usuario in Model)
                {
                    <tr>
                        <td class="td-first">@usuario.id_usuario</td>
                        <td class="td-middle">@usuario.nombre_completo</td>
                        <td class="td-middle">@usuario.fecha_registro.ToString("dd/MM/yyyy")</td>
                        @* <td class="td-middle">@usuario.correo</td>
                    <td class="td-middle">-----</td>
                    <td class="td-middle">------</td>
                    *@
                        <td class="td-end">
                            <div class="dropdown">
                                <button class="btn dropdown-toggle text-dark" type="button" id="dropdownMenuButton1"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fas fa-ellipsis-v"></i>
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                    @* <a class="dropdown-item" asp-controller="Home" asp-action="UsuarioDetalle">Contactar
                                a usuario</a>
                                <a class="dropdown-item" asp-controller="Home" asp-action="UsuarioDetalle">Enviar
                                Correo</a>
                                <a class="dropdown-item" asp-controller="Home" asp-action="UsuarioDetalle">Llamar</a> *@
                                    <a class="dropdown-item" data-bs-toggle="modal" data-bs-target="#deleteUserModal"
                                        data-name="@usuario.nombre_completo" data-id="@usuario.id_usuario">Dar de baja</a>
                                </div>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>

<div class="modal fade" id="deleteUserModal" tabindex="-1" aria-labelledby="deleteUserModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteUserModalLabel">Eliminar Usuario</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="deleteUserModalBody">
                ¿Estás seguro que deseas eliminar a este usuario?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-danger" id="confirmDeleteButton">Eliminar</button>
            </div>
        </div>
    </div>
</div>


<div class="modal fade modal-right" id="filterModal" tabindex="-1" aria-labelledby="filterModalLabel"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="rightModalLabel">Filtrar</h5>
                <button type="button" class="btn btn-link ms-auto me-3">Limpiar filtros</button>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="tipoCliente">Servicios</label>
                        <div class="input-group">
                            <select class="form-control" id="tipoCliente">
                                <option selected>Seleccionar...</option>
                                <option value="1">Cliente A</option>
                                <option value="2">Cliente B</option>
                                <option value="3">Cliente C</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="estatus">Estatus</label>
                        <div class="input-group">
                            <select class="form-control" id="estatus">
                                <option selected>Seleccionar...</option>
                                <option value="1">Activo</option>
                                <option value="2">Inactivo</option>
                                <option value="3">Pendiente</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="cumpleanos">Usuario</label>
                        <div class="input-group">
                            <div class="groupSearch">
                                <svg class="iconSearch" aria-hidden="true" viewBox="0 0 24 24">
                                    <g>
                                        <path
                                            d="M21.53 20.47l-3.66-3.66C19.195 15.24 20 13.214 20 11c0-4.97-4.03-9-9-9s-9 4.03-9 9 4.03 9 9 9c2.215 0 4.24-.804 5.808-2.13l3.66 3.66c.147.146.34.22.53.22s.385-.073.53-.22c.295-.293.295-.767.002-1.06zM3.5 11c0-4.135 3.365-7.5 7.5-7.5s7.5 3.365 7.5 7.5-3.365 7.5-7.5 7.5-7.5-3.365-7.5-7.5z">
                                        </path>
                                    </g>
                                </svg>
                                <input value="" name="searchTerm" placeholder="Busca por usuario/ID" type="search"
                                    class="inputSearch">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="cumpleanos">Proveedor</label>
                        <div class="input-group">
                            <div class="groupSearch">
                                <input value="" name="searchTerm" placeholder="Nombre" type="search"
                                    class="inputSearch">
                            </div>
                        </div>
                    </div>
                </form>
                <hr>
                <div class="filter-section">
                    <h6>Filtros aplicados</h6>
                    <div class="filters-applied">
                        <span class="tag">Tipo de Cliente <i class="fas fa-times close"></i></span>
                        <span class="tag">Buscar por Usuario <i class="fas fa-times close"></i></span>
                        <span class="tag">Estatus <i class="fas fa-times close"></i></span>
                        <span class="tag">Cumpleaños <i class="fas fa-times close"></i></span>
                    </div>
                </div>
                <button class="btn btn-primary w-100">Aplicar</button>
            </div>
        </div>
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


<script asp-append-version="true">
    document.addEventListener('DOMContentLoaded', function () {
        const searchInput = document.getElementById('searchInput');
        const table = document.querySelector('.table tbody');

        searchInput.addEventListener('keyup', function () {
            const searchTerm = searchInput.value.toLowerCase();
            const rows = table.querySelectorAll('tr');

            rows.forEach(function (row) {
                const idCell = row.querySelector('td:nth-child(1)');
                const nameCell = row.querySelector('td:nth-child(2)');

                const idText = idCell.textContent.toLowerCase();
                const nameText = nameCell.textContent.toLowerCase();

                if (idText.includes(searchTerm) || nameText.includes(searchTerm)) {
                    row.style.display = '';
                } else {
                    row.style.display = 'none';
                }
            });
        });


        const deleteUserModal = new bootstrap.Modal(document.getElementById('deleteUserModal'));
        const confirmDeleteButton = document.getElementById('confirmDeleteButton');
        let userIdToDelete;

        document.querySelectorAll('[data-bs-toggle="modal"]').forEach(function (button) {
            button.addEventListener('click', function () {
                userIdToDelete = this.getAttribute('data-id');
                name = this.getAttribute('data-name');
                deleteUserModalBody.innerText = `¿Estás seguro que deseas eliminar a ${name}?`;
            });
        });

        confirmDeleteButton.addEventListener('click', function () {
            Swal.fire({
                title: 'Eliminando',
                allowOutsideClick: false,
                allowEscapeKey: false,
                didOpen: () => {
                    Swal.showLoading();
                }
            })
            fetch(`/Usuarios/EliminarUsuario?idUsuario=${userIdToDelete}`, {
                method: 'DELETE',
                headers: {
                    'Content-Type': 'application/json'
                }
            })
                .then(response => {
                    if (!response.ok) {
                        throw new Error('Error al eliminar el usuario. Código de estado: ' + response.status);
                    }
                    return response.json();
                })
                .then(data => {
                    if (data) {
                        document.querySelector(`a[data-id="${userIdToDelete}"]`).closest('tr').remove();
                        deleteUserModal.hide();
                        Swal.fire({
                            icon: 'success',
                            title: 'Usuario eliminado',
                            text: 'El usuario ha sido eliminado exitosamente.',
                        });
                        setTimeout(() => {
                            window.location.reload();
                        }, 500);
                    }
                })
                .catch(error => {
                    // Muestra el error de forma más clara
                    Swal.fire({
                        icon: 'error',
                        title: 'Error',
                        text: error.message,
                    });
                }).finally(() => {
                    Swal.close();
                    deleteUserModal.hide();
                });
        });

    });
</script>
@section Scripts {
    <script>inicializarTable('#dataTable');</script>
    <script>
        filtrar('#dataTable', '', '', '', '', '');
    </script>
}