nunu_panel/Controllers/ProveedoresController.cs
using System.Collections.Generic;
using System.Diagnostics;
using System.Net;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using nunu_panel.Models;
using RestSharp;

namespace nunu_panel.Controllers
{
    public class ProveedoresController : Controller
    {
        private readonly ILogger<ProveedoresController> _logger;
        private static readonly string apiBaseUrl = "https://api-nunu.igrtec.net/api/";

        public ProveedoresController(ILogger<ProveedoresController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            var adminName = HttpContext.Session.GetString("AdminName");
            ViewBag.AdminName = adminName;
            var proveedores = GetProveedores();
            return View(proveedores?.OrderByDescending(p => p.id_proveedor).ToList());
        }

        [HttpDelete]
        public IActionResult EliminarProveedor(int idProveedor)
        {
            var options = new RestClientOptions(apiBaseUrl) { MaxTimeout = -1 };

            var client = new RestClient(options);
            var request = new RestRequest($"/Proveedores/{idProveedor}", Method.Delete);
            var response = client.Execute(request);

            if (response.StatusCode == HttpStatusCode.NoContent)
            {
                string? content = response.Content;
                TempData["SuccessMensajeUsuario"] =
                    content != null ? $"Proveedor {idProveedor} eliminado con éxito!" : null;
                return Json(new { success = true, message = TempData["SuccessMensajeUsuario"] });
            }
            else
            {
                string content = response.Content;
                _logger.LogError(content);
                TempData["ErrorMensajeUsuario"] =
                    $"Error al eliminar el proveedor desde la API. {response.StatusCode}";
                return Json(new { success = false, message = TempData["ErrorMensajeUsuario"] });
            }
        }

        [HttpPost]
        public IActionResult AprovarProveedor(int idProveedor)
        {
            var options = new RestClientOptions(apiBaseUrl) { MaxTimeout = -1 };

            var client = new RestClient(options);
            var request = new RestRequest(
                $"/Proveedores/VerificarProveedor/{idProveedor}",
                Method.Post
            );
            var response = client.Execute(request);

            if (response.StatusCode == HttpStatusCode.OK)
            {
                //verificar documentacion con strapi
                var strapiINE = new RestRequest(
                    $"/Proveedores/VerificarDocumentacionProveedor/{idProveedor}",
                    Method.Post
                );
                var strapiINEResponse = client.Execute(strapiINE);
                if (strapiINEResponse.StatusCode == HttpStatusCode.OK)
                {
                    return Ok(
                        new
                        {
                            success = true,
                            message = $"Proveedor {idProveedor} Aprobado con éxito"
                        }
                    );
                }
                else
                {
                    return BadRequest(
                        new
                        {
                            success = false,
                            message = "Error al aprobar el proveedor:{0}",
                            strapiINEResponse.Content
                        }
                    );
                }
            }
            else
            {
                var error = JsonConvert.DeserializeObject(response.Content);

                _logger.LogError(error?.ToString());

                return Json(
                    new
                    {
                        success = false,
                        message = $"Error al aprobar el proveedor desde la API. {error?.ToString()}"
                    }
                );
            }
        }

        [HttpPost("/Proveedores/RechazarProveedor/{idProveedor}/{razonRechazo}")]
        public async Task<IActionResult> RechazarProveedor(int idProveedor, string razonRechazo)
        {
            _logger.LogInformation($"Rechazar proveedor: {idProveedor} con motivo: {razonRechazo}");
            var options = new RestClientOptions(apiBaseUrl) { MaxTimeout = -1 };

            var client = new RestClient(options);
            var request = new RestRequest($"/Proveedores/RechazarProveedor", Method.Post);
            request.AddJsonBody(new { idProveedor, motivo = razonRechazo });
            var response = await client.ExecuteAsync(request);

            if (response.StatusCode == HttpStatusCode.OK)
            {
                return Ok(new { success = true, message = "Proveedor rechazado con éxito" });
            }
            else
            {
                return BadRequest(
                    new { success = false, message = "Error al rechazar el proveedor" }
                );
            }
        }

        [HttpPost("/Proveedores/PausarProveedor/{idProveedor}/{motivo}")]
        public IActionResult PausarProveedor(int idProveedor, string motivo)
        {
            _logger.LogInformation($"Pausar proveedor: {idProveedor} con motivo: {motivo}");
            var options = new RestClientOptions(apiBaseUrl) { MaxTimeout = -1 };

            var client = new RestClient(options);
            var request = new RestRequest($"/Proveedores/SuspenderProvedor", Method.Post);
            request.AddJsonBody(new { idProveedor, motivo });
            var response = client.Execute(request);
            if (response.StatusCode == HttpStatusCode.OK)
            {
                return Ok(new { success = true, message = "Proveedor pausado con éxito" });
            }
            else
            {
                return BadRequest(
                    new { success = false, message = "Error al pausar el proveedor" }
                );
            }
        }

        [HttpPost("/Proveedores/ReactivarProveedor/{idProveedor}/{motivo}")]
        public async Task<IActionResult> ReactivarProveedor(
            int idProveedor,
            string? motivo = "Usuario Reactivado"
        )
        {
            var options = new RestClientOptions(apiBaseUrl) { MaxTimeout = -1 };

            var client = new RestClient(options);
            var request = new RestRequest($"/Proveedores/ActivarProvedor", Method.Post);
            request.AddJsonBody(new { idProveedor, motivo });
            var response = await client.ExecuteAsync(request);
            if (response.StatusCode == HttpStatusCode.OK)
            {
                return Ok(new { success = true, message = "Proveedor reactivado con éxito" });
            }
            else
            {
                return BadRequest(
                    new { success = false, message = "Error al reactivar el proveedor" }
                );
            }
        }

        public List<ProveedorModel>? GetProveedores()
        {
            try
            {
                var options = new RestSharp.RestClientOptions(apiBaseUrl) { MaxTimeout = -1 };

                var client = new RestSharp.RestClient(options);
                var request = new RestSharp.RestRequest("/Proveedores", Method.Get);
                var response = client.Execute<List<ProveedorModel>>(request);
                if (response.StatusCode == HttpStatusCode.OK)
                {
                    string? content = response.Content;
                    List<ProveedorModel>? proveedores = JsonConvert.DeserializeObject<
                        List<ProveedorModel>
                    >(content);
                    return proveedores;
                }
                else
                {
                    return null;
                }
            }
            catch
            {
                return null;
            }
        }

        public IActionResult Historial()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(
                new ErrorViewModel
                {
                    RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
                }
            );
        }
    }
}

nunu_panel/Controllers/ServiciosController.cs
using System.Collections.Generic;
using System.Diagnostics;
using System.Net;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using nunu_panel.Models;
using RestSharp;

namespace nunu_panel.Controllers
{
    public class ServiciosController : Controller
    {
        private readonly ILogger<ServiciosController> _logger;

        private static readonly string apiBaseUrl = "https://api-nunu.igrtec.net/api/";

        public ServiciosController(ILogger<ServiciosController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            var adminName = HttpContext.Session.GetString("AdminName");
            ViewBag.AdminName = adminName;
            var servicios = GetServicios();
            return View(servicios);
        }

        public List<ServicioProveedorModel>? GetServicios()
        {
            try
            {
                var options = new RestSharp.RestClientOptions(apiBaseUrl) { MaxTimeout = -1 };

                var client = new RestSharp.RestClient(options);
                var request = new RestSharp.RestRequest("/Servicios", Method.Get);
                var response = client.Execute<List<ServicioProveedorModel>>(request);
                if (response.StatusCode == HttpStatusCode.OK)
                {
                    string? content = response.Content;
                    List<ServicioProveedorModel>? serv = JsonConvert.DeserializeObject<
                        List<ServicioProveedorModel>
                    >(content);
                    return serv;
                }
                else
                {
                    return null;
                }
            }
            catch
            {
                return null;
            }
        }

        [HttpDelete]
        public IActionResult EliminarServicio(int idServicio)
        {
            var options = new RestClientOptions(apiBaseUrl) { MaxTimeout = -1 };

            var client = new RestClient(options);
            var request = new RestRequest($"/Servicios/{idServicio}", Method.Delete);
            var response = client.Execute(request);

            if (response.StatusCode == HttpStatusCode.NoContent)
            {
                string? content = response.Content;
                TempData["SuccessMensajeUsuario"] =
                    content != null ? $"Servicio {idServicio} eliminado con éxito!" : null;
                return Json(new { success = true, message = TempData["SuccessMensajeUsuario"] });
            }
            else
            {
                TempData["ErrorMensajeUsuario"] =
                    $"Error al eliminar el servicio desde la API. {response.StatusCode}";
                return Json(new { success = false, message = TempData["ErrorMensajeUsuario"] });
            }
        }

        public IActionResult Historial()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(
                new ErrorViewModel
                {
                    RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
                }
            );
        }
    }
}

nunu_panel/Views/Servicios/Historial.cshtml
@{
    ViewData["Title"] = "Estado Proveedor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
 <a asp-controller="Servicios" asp-action="Index" class="btn btn-link mt-1" style="color: gray;">
     <i class="fas fa-arrow-left"></i> Volver
 </a>
<div class="row mb-3">
    <div class="col">
        <form asp-controller="Servicios" asp-action="Index">
            <div class="groupSearch">
                <svg class="iconSearch" aria-hidden="true" viewBox="0 0 24 24"><g><path d="M21.53 20.47l-3.66-3.66C19.195 15.24 20 13.214 20 11c0-4.97-4.03-9-9-9s-9 4.03-9 9 4.03 9 9 9c2.215 0 4.24-.804 5.808-2.13l3.66 3.66c.147.146.34.22.53.22s.385-.073.53-.22c.295-.293.295-.767.002-1.06zM3.5 11c0-4.135 3.365-7.5 7.5-7.5s7.5 3.365 7.5 7.5-3.365 7.5-7.5 7.5-7.5-3.365-7.5-7.5z"></path></g></svg>
                <input value="" name="searchTerm" placeholder="Busca por ciudad, proveedor" type="search" class="inputSearch">
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="d-flex justify-content-between align-items-center">
        <h4 class="title-form">Listado de proveedores pertenenciantes al servicio de diseño</h4>
        <div>
        <button type="button" class="btn btn-filter" data-bs-toggle="modal" data-bs-target="#filterModal">
            <i class="fas fa-filter"></i> <!-- Icono de filtro -->
        </button>
        </div>
        
    </div>
</div>

<div class="row">
    <div class="breadcrumb">
        <a href="/Servicios" class="breadcrumb-item active">Servicios</a> >
    </div>
    Mostrando 7 de 100 resultados
</div>

<div class="col-md-12 mt-3">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col" class="">ID</th>
                    <th scope="col" class="">Servicio</th>
                    <th scope="col" class="">Proveedores</th>
                    <th scope="col" class="">Ciudad</th>
                    <th scope="col" class=""></th>
                </tr>
            </thead>
            <tbody> 
                <tr>                  
                    <td class="td-first">
                        000001
                    </td>
                    <td class="td-middle">Diseño</td>
                    <td class="td-middle"><a asp-controller="Proveedores" asp-action="Historial">Ver Estado</a></td>                                                                                
                    <td class="td-middle">Lorep ipsum</td>
                    <td class="td-end">
                        <div class="dropdown">
                            <button class="btn dropdown-toggle text-dark" type="button" id="dropdownMenuButton1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-ellipsis-v"></i>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                <a class="dropdown-item" asp-controller="Home" asp-action="UsuarioDetalle">Contactar a proveedor</a>
                                <a class="dropdown-item" asp-controller="Home" asp-action="UsuarioDetalle">Enviar Correo</a>
                                <a class="dropdown-item" asp-controller="Home" asp-action="UsuarioDetalle">Llamar</a>
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>                  
                    <td class="td-first">
                        000001
                    </td>
                    <td class="td-middle">Diseño</td>
                    <td class="td-middle"><a asp-controller="Proveedores" asp-action="Historial">Ver Estado</a></td>                                                                                
                    <td class="td-middle">Lorep ipsum</td>
                    <td class="td-end">
                        <div class="dropdown">
                            <button class="btn dropdown-toggle text-dark" type="button" id="dropdownMenuButton1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-ellipsis-v"></i>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                <a class="dropdown-item" asp-controller="Home" asp-action="UsuarioDetalle">Contactar a proveedor</a>
                                <a class="dropdown-item" asp-controller="Home" asp-action="UsuarioDetalle">Enviar Correo</a>
                                <a class="dropdown-item" asp-controller="Home" asp-action="UsuarioDetalle">Llamar</a>
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>                  
                    <td class="td-first">
                        000001
                    </td>
                    <td class="td-middle">Diseño</td>
                    <td class="td-middle"><a asp-controller="Proveedores" asp-action="Historial">Ver Estado</a></td>                                                                                
                    <td class="td-middle">Lorep ipsum</td>
                    <td class="td-end">
                        <div class="dropdown">
                            <button class="btn dropdown-toggle text-dark" type="button" id="dropdownMenuButton1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-ellipsis-v"></i>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                <a class="dropdown-item" asp-controller="Home" asp-action="UsuarioDetalle">Contactar a proveedor</a>
                                <a class="dropdown-item" asp-controller="Home" asp-action="UsuarioDetalle">Enviar Correo</a>
                                <a class="dropdown-item" asp-controller="Home" asp-action="UsuarioDetalle">Llamar</a>
                            </div>
                        </div>
                    </td>
                </tr>

            
            </tbody>
        </table>
    </div>
</div>



<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="calificacionodalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title fw-bolder fs-3" id="estatusModalLabel">Calificación Del Servicio</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="">Nombre Del Servicio</label>
                    <input type="text" class="form-control" value="Nuevo" readonly>
                </div>
                <div class="form-group">
                    <label for="">Ciudad</label>
                    <input type="text" class="form-control" value="00/00" readonly>
                </div>
                <button class="btn btn-primary w-100">Guardar</button>
            </div>
        </div>
    </div>
</div>



<div class="modal fade modal-right" id="filterModal" tabindex="-1" aria-labelledby="filterModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="rightModalLabel">Filtrar</h5>
                <button type="button" class="btn btn-link ms-auto me-3">Limpiar filtros</button>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="tipoCliente">Servicios</label>
                        <div class="input-group">
                            <select class="form-control" id="tipoCliente">
                                <option selected>Seleccionar...</option>
                                <option value="1">Cliente A</option>
                                <option value="2">Cliente B</option>
                                <option value="3">Cliente C</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="estatus">Estatus</label>
                        <div class="input-group">
                            <select class="form-control" id="estatus">
                                <option selected>Seleccionar...</option>
                                <option value="1">Activo</option>
                                <option value="2">Inactivo</option>
                                <option value="3">Pendiente</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="cumpleanos">Usuario</label>
                        <div class="input-group">
                            <div class="groupSearch">
                                <svg class="iconSearch" aria-hidden="true" viewBox="0 0 24 24"><g><path d="M21.53 20.47l-3.66-3.66C19.195 15.24 20 13.214 20 11c0-4.97-4.03-9-9-9s-9 4.03-9 9 4.03 9 9 9c2.215 0 4.24-.804 5.808-2.13l3.66 3.66c.147.146.34.22.53.22s.385-.073.53-.22c.295-.293.295-.767.002-1.06zM3.5 11c0-4.135 3.365-7.5 7.5-7.5s7.5 3.365 7.5 7.5-3.365 7.5-7.5 7.5-7.5-3.365-7.5-7.5z"></path></g></svg>
                                <input value="" name="searchTerm" placeholder="Busca por usuario/ID" type="search" class="inputSearch">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="cumpleanos">Proveedor</label>
                        <div class="input-group">
                            <div class="groupSearch">                                
                                <input value="" name="searchTerm" placeholder="Nombre" type="search" class="inputSearch">
                            </div>
                        </div>
                    </div>
                </form>
                <hr>
                <div class="filter-section">
                    <h6>Filtros aplicados</h6>
                    <div class="filters-applied">
                        <span class="tag">Tipo de Cliente <i class="fas fa-times close"></i></span>
                        <span class="tag">Buscar por Usuario <i class="fas fa-times close"></i></span>
                        <span class="tag">Estatus <i class="fas fa-times close"></i></span>
                    </div>
                </div>
                <button class="btn btn-primary w-100">Aplicar</button>
            </div>
        </div>
    </div>
</div>