nunu_panel/Controllers/CategoriasController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using nunu_panel.Models;
using RestSharp;

namespace nunu_panel.Controllers;

public class CategoriasController : Controller
{
    private static readonly string apiBaseUrl = "https://api-nunu.igrtec.net/api/";

    private static readonly RestClientOptions options = new RestClientOptions(apiBaseUrl)
    {
        MaxTimeout = -1
    };

    private static readonly RestClient client = new RestClient(options);

    public async Task<IActionResult> Index()
    {
        var request = new RestRequest("/Categorias");
        var response = await client.ExecuteAsync(request);

        string? content = response.Content ?? "[]";
        var model = JsonConvert.DeserializeObject<List<CategoriaModel>>(content);

        model ??= new List<CategoriaModel>();

        return View(model);
    }

    public IActionResult Nueva()
    {
        return View(new CategoriaModel());
    }

    [HttpPost]
    public async Task<IActionResult> Nueva(CategoriaModel model)
    {
        if (ModelState.IsValid)
        {
            var request = new RestRequest("/Categorias", Method.Post);

            request.AddParameter("Categoria", model.categoria);

            if (model.Imagen != null)
            {
                using var ms = new MemoryStream();
                model.Imagen.CopyTo(ms);
                byte[] bytes = ms.ToArray();
                request.AddFile("Imagen_Categoria", bytes, model.Imagen.FileName);
            }

            var response = await client.ExecuteAsync(request);

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            Console.WriteLine("Error creando la categoría: " + response.StatusDescription);

            ModelState.AddModelError(
                string.Empty,
                "No se pudo crear la nueva categoría de servicios, por favor, inténtelo más tarde."
            );
        }

        return View(model);
    }

    public async Task<IActionResult> Editar(int id)
    {
        var request = new RestRequest($"/Categorias/{id}");
        var response = await client.ExecuteAsync(request);

        if (!response.IsSuccessStatusCode)
        {
            Console.WriteLine($"Categoría no encontrada {id}: " + response.StatusDescription);

            return RedirectToAction("Index");
        }

        var content = response.Content ?? "[]";
        var model = JsonConvert.DeserializeObject<CategoriaModel>(content);

        model ??= new CategoriaModel();

        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> Editar(CategoriaModel model)
    {
        if (ModelState.IsValid)
        {
            int id = model.id_categoria;

            var request = new RestRequest($"/Categorias/{id}", Method.Put);

            request.AddParameter("categoria.Categoria", model.categoria);

            if (model.Imagen != null)
            {
                using var ms = new MemoryStream();
                model.Imagen.CopyTo(ms);
                byte[] bytes = ms.ToArray();
                request.AddFile("categoria.Imagen_Categoria", bytes, model.Imagen.FileName);
            }

            var response = await client.ExecuteAsync(request);

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            Console.WriteLine("Error actualizando la categoría: " + response.StatusDescription);

            ModelState.AddModelError(
                string.Empty,
                "No se pudo actualizar la categoría de servicios, por favor, inténtelo más tarde."
            );
        }

        return View(model);
    }

    public async Task<IActionResult> Eliminar(int id)
    {
        var request = new RestRequest($"/Categorias/{id}", Method.Delete);
        var response = await client.ExecuteAsync(request);

        if (!response.IsSuccessStatusCode)
        {
            Console.WriteLine($"Categoría no eliminada {id}: " + response.StatusDescription);
        }

        return RedirectToAction("Index");
    }
}

nunu_panel/Views/Categorias/Editar.cshtml
@model CategoriaModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Editar categoría";
}

<div class="container">
    <a asp-controller="Categorias" asp-action="Index" class="btn btn-link mt-1" style="color: gray;">
        <i class="fas fa-arrow-left"></i> Volver
    </a>

    <h3 class="mt-4">Editar categoría</h3>

    <div class="row mb-3">
        <div class="col-md-12 div-nav-pages">
            <span>Categorías <strong>></strong> Categoría @Model.id_categoria</span>
        </div>
    </div>

    <div class="row">
        <div class="col-6">
            <form asp-action="Editar" method="post" enctype="multipart/form-data">

                <div asp-validation-summary="All" class="text-danger"></div>

                <div class="mb-3">
                    <label class="form-label">Nombre de la categoría</label>
                    <input asp-for="categoria" type="text" class="form-control" placeholder="Anterior: @Model.categoria" required>
                    <span asp-validation-for="categoria" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <img id="imagePreview" alt="" width="300" src="@Model.imagen_Categoria" />
                    <input asp-for="Imagen" class="form-control mt-2" width="30px" accept="image/*" onchange="previewImage(event)">
                    <span asp-validation-for="Imagen" class="text-danger"></span>
                </div>

                <div class="d-flex justify-content-between mt-2">
                    <button type="submit" class="btn btn-success">
                        <i class="fas fa-save"></i> Guardar
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    function previewImage(event) {
        const reader = new FileReader();
        reader.onload = function () {
            const output = document.getElementById('imagePreview');
            output.src = reader.result;
        };
        reader.readAsDataURL(event.target.files[0]);
    }
</script>
<script>
    /*window.onload = function() {
        console.log('Loading...');

        const img = new Image();
        img.onload = imagePreviewOnLoad
        img.src = imagePreview.src
        //img.crossOrigin = "Anonymous"
    };

    function imagePreviewOnLoad() {
        console.log('Loading image...');

        const canvas = document.createElement('canvas');
        const ctx = canvas.getContext('2d');

        // Ajustar el tamaño del canvas al tamaño de la imagen
        canvas.width = imagePreview.width;
        canvas.height = imagePreview.height;

        // Dibujar la imagen en el canvas
        ctx.drawImage(imagePreview, 0, 0);

        canvas.toBlob((blob) => {
            // Get file name.
            const regex = /.*(\S+\.\S+)$/g;
            const result = regex.exec(imagePreview.src);
            const filename = result[1] ?? 'image.jpg';

            console.log('Nombre de archivo de la imagen: ', filename);

            // Create a new File from the Blob
            const file = new File([blob], filename, { type: blob.type });

            // Create a DataTransfer object to simulate a user selecting a file
            const dataTransfer = new DataTransfer();
            dataTransfer.items.add(file);

            // Set the file input's files to the new file
            fileInput.files = dataTransfer.files;

            console.log("File set successfully");
        });
    }*/
</script>

<script src="https://cdn.jsdelivr.net/npm/@@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js"></script>
<!-- Scripts de Bootstrap y Popper.js -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>

nunu_panel/Views/Categorias/Index.cshtml
@model List<CategoriaModel>

@{
    ViewData["Title"] = "Categorías de servicios";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles {
    <link rel="stylesheet" href="/css/categorias.css" type="text/css">
}

<div class="container">
    <div class="row mb-3">
        <div class="col-md-12">
            <div class="form-group">
                <input type="text" name="" id="searchInput" class="form-control" placeholder="Busca por categoria">
            </div>
            @* <form asp-action="Index">
            <div class="groupSearch">
                <svg class="iconSearch" aria-hidden="true" viewBox="0 0 24 24"><g><path d="M21.53 20.47l-3.66-3.66C19.195 15.24 20 13.214 20 11c0-4.97-4.03-9-9-9s-9 4.03-9 9 4.03 9 9 9c2.215 0 4.24-.804 5.808-2.13l3.66 3.66c.147.146.34.22.53.22s.385-.073.53-.22c.295-.293.295-.767.002-1.06zM3.5 11c0-4.135 3.365-7.5 7.5-7.5s7.5 3.365 7.5 7.5-3.365 7.5-7.5 7.5-7.5-3.365-7.5-7.5z"></path></g></svg>
                <input value="" id="searchInput" name="searchTerm" placeholder="Busca en categorías" type="search" class="inputSearch">
            </div>
        </form> *@
        </div>
    </div>

    <div class="row">
        <div class="d-flex justify-content-between align-items-center">
            <h4 class="title-form">Categorías</h4>
        </div>
    </div>

    <div class="row">
        <div class="breadcrumb">
            <a href="/Categorias" class="breadcrumb-item active">Categorías</a> > Todas
        </div>
        @* Mostrando @Model.Count *@
    </div>

    <div class="col-md-12 mt-3">

        <a class="btn btn-primary" asp-action="Nueva">
            Nueva categoría
        </a>

        <table class="table" id="dataTable">
            @* <colgroup>
        <col style="width:60px"/>
        <col style="width:auto"/>
        <col style="width:50px"/>
    </colgroup> *@
            <thead>
                <tr>
                    <th scope="col" class="">Imagen</th>
                    <th scope="col" class="">Nombre</th>
                    <th scope="col" class="textTableCenter"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var categoria in Model)
                {
                    <tr>
                        <td class="td-first">
                            <img class="squircle-icon" src="@categoria.imagen_Categoria">
                        </td>
                        <td class="td-middle">@categoria.categoria</td>
                        <td class="td-end">
                            <div class="dropdown">
                                <button class="btn dropdown-toggle text-dark" type="button" id="dropdownMenuButton1"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fas fa-ellipsis-v"></i>
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                    @*<a class="dropdown-item"
                                asp-action="Editar"
                                asp-route-id="@categoria.id_categoria">
                                Editar
                                </a>*@
                                    <a class="dropdown-item" data-bs-toggle="modal" data-bs-target="#deleteCatModal"
                                        onclick="setDeleteModalId(@categoria.id_categoria)">
                                        Eliminar
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>

<div class="modal fade" id="deleteCatModal" tabindex="-1" aria-labelledby="deleteCatModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form asp-action="Eliminar">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteCatModalLabel">Eliminar Categoría</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    ¿Estás seguro que deseas eliminar esta categoría?
                    <input type="hidden" name="id" id="deleteCatModalId">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-danger">Eliminar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const searchInput = document.getElementById('searchInput');
        const table = document.querySelector('.table tbody');

        searchInput.addEventListener('keyup', function () {
            const searchTerm = searchInput.value.toLowerCase();
            const rows = table.querySelectorAll('tr');

            rows.forEach(function (row) {
                const idCell = row.querySelector('td:nth-child(1)');
                const nameCell = row.querySelector('td:nth-child(2)');

                const idText = idCell.textContent.toLowerCase();
                const nameText = nameCell.textContent.toLowerCase();

                if (idText.includes(searchTerm) || nameText.includes(searchTerm)) {
                    row.style.display = '';
                } else {
                    row.style.display = 'none';
                }
            });
        });
    });
</script>

<script>
    function setDeleteModalId(id) {
        deleteCatModalId.value = id
    }
</script>
@section Scripts {

    <script>
        inicializarTable('#dataTable');
        filtrar('#dataTable', '', '', '', '', '')
    </script>
}

nunu_panel/Views/Categorias/Nueva.cshtml
@model CategoriaModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Nueva categoría";
}

<div class="container">
    <a asp-controller="Categorias" asp-action="Index" class="btn btn-link mt-1" style="color: gray;">
        <i class="fas fa-arrow-left"></i> Volver
    </a>

    <h3 class="mt-4">Agregar nueva categoría</h3>

    <div class="row mb-3">
        <div class="col-md-12 div-nav-pages">
            <span>Categorías <strong>></strong> Agregar categoría</span>
        </div>
    </div>

    <div class="row">
        <div class="col-6">
            <form asp-action="Nueva" method="post" enctype="multipart/form-data">

                <div asp-validation-summary="All" class="text-danger"></div>

                <div class="mb-3">
                    <input asp-for="id_categoria" type="hidden" readonly>
                    <label class="form-label">Nombre de la categoría</label>
                    <input asp-for="categoria" type="text" class="form-control" required>
                    <span asp-validation-for="categoria" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <img id="imagePreview" src="" alt="" width="300" />
                    <input asp-for="Imagen" class="form-control mt-2" width="30px" accept="image/*" onchange="previewImage(event)" required>
                    <span asp-validation-for="Imagen" class="text-danger"></span>
                </div>

                <div class="d-flex justify-content-between mt-2">
                    <button type="submit" class="btn btn-success">
                        <i class="fas fa-save"></i> Guardar
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    function previewImage(event) {
        const reader = new FileReader();
        reader.onload = function () {
            const output = document.getElementById('imagePreview');
            output.src = reader.result;
        };
        reader.readAsDataURL(event.target.files[0]);
    }
</script>

<script src="https://cdn.jsdelivr.net/npm/@@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js"></script>
<!-- Scripts de Bootstrap y Popper.js -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>