nunu_panel/Controllers/LoginController.cs
using System.Collections.Generic;
using System.Diagnostics;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using nunu_panel.Models;
using RestSharp;

namespace nunu_panel.Controllers
{
    public class LoginController : Controller
    {
        private readonly ILogger<LoginController> _logger;
        private static readonly string apiBaseUrl = "https://api-nunu.igrtec.net/api/";

        public LoginController(ILogger<LoginController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public IActionResult Index(string? error)
        {
            ViewBag.Error = error;
            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginModel loginModel)
        {
            var options = new RestClientOptions(apiBaseUrl) { MaxTimeout = -1 };
            var client = new RestClient(options);
            var request = new RestRequest("/Administradores/login", Method.Post);
            request.AddHeader("Content-Type", "application/json");

            var st = new { correo = loginModel.correo, contraseña = loginModel.contrasena };
            string jsn = JsonConvert.SerializeObject(st);
            request.AddJsonBody(jsn, ContentType.Json);
            var response = client.Execute(request);

            if (
                response.StatusCode == HttpStatusCode.Created
                || response.StatusCode == HttpStatusCode.OK
            )
            {
                var admin = JsonConvert.DeserializeObject<AdminResponse>(response.Content);

                HttpContext.Session.SetInt32("AdminId", admin.id_admin);
                HttpContext.Session.SetString("AdminName", admin.nombre);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                //ModelState.AddModelError(string.Empty, "Correo o contraseña incorrectos");
                return RedirectToAction(
                    nameof(Index),
                    new { error = "Correo o contraseña incorrectos" }
                );
            }
        }

        public class TokenResponse
        {
            public string AccessToken { get; set; }
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(
                new ErrorViewModel
                {
                    RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
                }
            );
        }
    }
}

nunu_panel/Views/Login/index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}
<style>
    body,
    html {
        height: 100%;
        margin: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        background-color: #f8f9fa;
    }

    .password-icon {
        cursor: pointer;
        position: absolute;
        top: 50%;
        right: 10px;
        transform: translateY(-50%);
    }

    .google-login-btn {
        width: 300px;
        margin: auto;
        margin-top: 20px;
        display: flex;
        align-items: center;
        padding: 3px;
        font-size: 1rem;
        border: 1px solid #ccc;
        border-radius: 4px;
        background-color: #0d6efd;
        color: #ffffff;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

    .google-login-btn:hover {
        background-color: #1891c6;
    }

    .google-login-btn img {
        margin-right: 20px;
        height: 50px;
    }

    .login-box {
        background: white;
        padding: 40px;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        text-align: center;
        width: 500px;
    }

    .logo_img {
        width: 100px;
        margin-bottom: 20px;
    }

    .login-box .form-group {
        text-align: left;
    }

    .input-group-append .fa {
        cursor: pointer;
    }

    .toggle-password {
        cursor: pointer;
    }

    .clear-password {
        cursor: pointer;
    }

    .btn-login {
        width: 100%;
        padding: 10px;
        background-color: #2577e7;
        color: #000;
        font-weight: 500;
        border: none;
        border-radius: 20px;
        font-size: 16px;
        margin-top: 20px;
    }

    .login-box input {
        border: 3px solid #2577e7;
    }
</style>


<div class="login-box">

    <img src="~/img/logo.png" class="logo_img" alt="Logo">
    <h2>Inicia sesión</h2>
    <form asp-controller="Login" asp-action="Login" method="post">
        <div class="form-group">
            <label for="correo">Correo</label>
            <input type="email" class="form-control" id="correo" name="correo" required>
        </div>

        <div class="form-group">
            <label for="contrasena">Contraseña</label>
            <div class="input-group">
                <input type="password" class="form-control" id="contrasena" name="contrasena" required>
                <span class="password-icon toggle-password" id="togglePassword" onclick="togglePasswordVisibility()">
                    <i class="fas fa-eye"></i>
                </span>
            </div>

        </div>

        <button class="btn-login" type="submit">INICIAR SESIÓN</button>
    </form>

    @if (ViewBag.Error != null)
    {
        <div class="alert alert-danger mt-2" role="alert">
            @ViewBag.Error
        </div>
    }
</div>

<script>
    function togglePasswordVisibility() {
        var passwordInput = document.getElementById('contrasena');
        var passwordIcon = document.querySelector('.toggle-password i');
        if (passwordInput.type === 'password') {
            passwordInput.type = 'text';
            passwordIcon.classList.remove('fa-eye');
            passwordIcon.classList.add('fa-eye-slash');
        } else {
            passwordInput.type = 'password';
            passwordIcon.classList.remove('fa-eye-slash');
            passwordIcon.classList.add('fa-eye');
        }
    }

    function clearPassword() {
        document.getElementById('contrasena').value = '';
    }
</script>